// <auto-generated />
using System;
using DepozitApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepozitApp.Migrations
{
    [DbContext(typeof(DepozitContext))]
    [Migration("20220930130300_renameTable")]
    partial class renameTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DepozitApp.Command", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CommandId")
                        .HasColumnType("int")
                        .HasColumnName("Command_Id");

                    b.Property<int?>("CountProdus")
                        .HasColumnType("int")
                        .HasColumnName("Count_Produs");

                    b.Property<DateTime?>("DataChange")
                        .HasColumnType("date");

                    b.Property<bool?>("Export")
                        .HasColumnType("bit");

                    b.Property<bool?>("Import")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.ToTable("Command", (string)null);
                });

            modelBuilder.Entity("DepozitApp.Produ", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Owner")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("DepozitApp.Command", b =>
                {
                    b.HasOne("DepozitApp.Produ", "CommandNavigation")
                        .WithMany("Commands")
                        .HasForeignKey("CommandId")
                        .HasConstraintName("FK__Command__Command__276EDEB3");

                    b.Navigation("CommandNavigation");
                });

            modelBuilder.Entity("DepozitApp.Produ", b =>
                {
                    b.Navigation("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
